CREATE TABLE PROYECTOS
(
    ID_PROYECTO             INTEGER NOT NULL,
    NOMBRE                  VARCHAR2(50),
    FECHA_INICIO_PROYECTO   DATE,
    FECHA_FIN_PROYECTO      DATE,
    FECHA_CREACION_REG      DATE,
    FECHA_MODIFICACION_REG  DATE
)
;
/

ALTER TABLE PROYECTOS ADD CONSTRAINT PK_PROYECTOS 
   PRIMARY KEY (ID_PROYECTO) 
 USING INDEX 
;
/

CREATE TABLE MATERIALES
(
	ID_MATERIAL             INTEGER NOT NULL,
	NOMBRE                  VARCHAR2(7),
	CANT_DISPONIBLE         NUMBER,
	FECHA_CREACION_REG      DATE,
	FECHA_MODIFICACION_REG  DATE
)
;
/

ALTER TABLE MATERIALES ADD CONSTRAINT PK_MATERIALES 
	PRIMARY KEY (ID_MATERIAL) 
 USING INDEX 
;
/

CREATE TABLE CONSTRUCCIONES
(
	ID_CONSTRUCCION         INTEGER NOT NULL,
	ID_PROYECTO             INTEGER,
	NOMBRE                  VARCHAR2(20),
	FECHA_CREACION_REG      DATE,
	FECHA_MODIFICACION_REG  DATE
)
;
/


ALTER TABLE CONSTRUCCIONES ADD CONSTRAINT PK_CONSTRUCCIONES 
	PRIMARY KEY (ID_CONSTRUCCION) 
 USING INDEX 
;
/

ALTER TABLE CONSTRUCCIONES ADD CONSTRAINT FK_CONSTRUCCIONES_PROYECTOS 
	FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTOS (ID_PROYECTO)
;
/

CREATE TABLE SOLICITUDES
(
	ID_SOLICITUD               INTEGER NOT NULL,
	ID_CONSTRUCCION            INTEGER,
	ESTADO                     VARCHAR2(10),
	COORDENADAS_CONSTRUCCION   VARCHAR2(100),
	FECHA_INICIO_CONSTRUCCION  DATE,
	FECHA_FIN_CONSTRUCCION     DATE,
	FECHA_CREACION_REG         DATE,
	FECHA_MODIFICACION_REG     DATE
)
;
/


ALTER TABLE SOLICITUDES ADD CONSTRAINT PK_SOLICITUDES 
	PRIMARY KEY (ID_SOLICITUD) 
 USING INDEX 
;
/

ALTER TABLE SOLICITUDES ADD CONSTRAINT FK_SOLICITUDES_CONSTRUCCIONES 
	FOREIGN KEY (ID_CONSTRUCCION) REFERENCES CONSTRUCCIONES (ID_CONSTRUCCION)
;
/

CREATE TABLE PARAMETROS_CONSTRUCCION
(
	ID_PARAMETRO            INTEGER NOT NULL,
	ID_CONSTRUCCION         INTEGER,
	CANT_CEMENTO            NUMBER,
	CANT_GRAVA              NUMBER,
	CANT_ARENA              NUMBER,
	CANT_MADERA             NUMBER,
	CANT_ADOBE              NUMBER,
	FECHA_CREACION_REG      DATE,
	FECHA_MODIFICACION_REG  DATE,
	DURACION_CONSTRUCCION   NUMBER
)
;
/


ALTER TABLE PARAMETROS_CONSTRUCCION ADD CONSTRAINT PK_PARAMETROS_CONSTRUCCION 
	PRIMARY KEY (ID_PARAMETRO) 
 USING INDEX 
;
/

ALTER TABLE PARAMETROS_CONSTRUCCION ADD CONSTRAINT FK_PARAMETROS_CONSTRUCCION_CONSTRUCCIONES 
	FOREIGN KEY (ID_CONSTRUCCION) REFERENCES CONSTRUCCIONES (ID_CONSTRUCCION)
;
/







